### ISSUE TITLE
Source code for download-canceler

### ISSUE THREAD

**Issue by ike08** [igorlogius/not-on-amo#2]
Hi, [download-canceler-1.0.5.xpi](https://github.com/igorlogius/not-on-amo/blob/main/download-canceler-1.0.5.xpi) is great; nice work. Do you have the source code available anywhere? Thanks

**Comment by igorlogius** [comment]
You can just extract the source from the xpi.
Just change the extension from xpi to zip and you can extract it.

FYI: Bug reports or suggestions for the xpi's are welcome too.
