### ISSUE TITLE
[Copy Selections with Linebreaks]  add custom multi selection seperators (spaces, semi-colons, line breaks) 

### ISSUE THREAD

**Issue by Bamajon1974** [igorlogius/not-on-amo#5]
Good morning

For copy_selections_with_linebreaks-1.0.0, after multiple non-contiguous selections are made on a webpage, it may be useful to have a submenu that places spaces, semi-colons, bullets and/or line breaks between selections. 

Thanks!

**Comment by igorlogius** [comment]
DevNote: need to re-add the option page for users so they can add their own seperators, ref. "copy links extras"

**Comment by igorlogius** [comment]
https://github.com/igorlogius/not-on-amo/assets/67047467/d24316e2-8e1b-49b3-84a4-8961492044ef

**Comment by igorlogius** [comment]
New addon: "Copy Selections"

![Screenshot_2024-01-01_16-08-54](https://github.com/igorlogius/not-on-amo/assets/67047467/197388b6-e37d-4097-aa3b-ef10fb04e6a6)

xpi will be added to the repo, when AMO signing is finished

**Comment by igorlogius** [comment]
Done:  https://github.com/igorlogius/not-on-amo/blob/main/copy-selections-1.0.0.xpi

**Comment by Bamajon1974** [comment]
Thank you. I will check out the modifications shortly and let you know if everything is ok. 

-JW

**Comment by Bamajon1974** [comment]
I tested the extension and didn't run into any issues. The default separators work and I even added in line spaces and colons as additional separators and they work as well. 

Only thing I found is a typo on the extension options page: "Seperator" should be "Separator"

Thanks!

**Comment by igorlogius** [comment]
Glad to hear. 

I'll make a note about the typo, but since it's not a major thing, i'll get to it at a later time. 

Thank you very much for the feedback.
If you find anything else, please dont hesitate to open a issue for it. :heart: 

Have a nice day and see you around.
