### ISSUE TITLE
[toolbar_countdown] Countdown does not start

### ISSUE THREAD

**Issue by Vingolf** [igorlogius/not-on-amo#8]
Hi igorlogius,

I've added [toolbar_countdown-1.1.8.xpi](https://github.com/igorlogius/not-on-amo/blob/main/toolbar_countdown-1.1.8.xpi) to an old FF Version but the countdown does not start  😢.

**What I have done:**

1. Download of  [toolbar_countdown-1.1.8.xpi](https://github.com/igorlogius/not-on-amo/blob/main/toolbar_countdown-1.1.8.xpi)
2. Add this file to

- Firefox 91.13.0esr

-  on Win 7 (32 bit)

3. The addon appears and I can set the countdown.

**Expected behavior**

The countdown should start 🤠, but it does not 😢.

Does this addon have other system requirements 🤔?

Regards,
Vingolf

**Comment by igorlogius** [comment]
> Does this addon have other system requirements 🤔?

No really. 

First, please try creating a second empty new profile and check if the addon works there without doing any modifications except adding the addon. Report back with your results.

**Comment by igorlogius** [comment]
no feedback, so i assume the issue has been resolved
